### ISSUE TITLE
Can't find Google

### ISSUE THREAD

**Issue by MatthieuScarset** [kevinquillen/drupal-goggles#2]
It seems this google might be private or not available anymore.

Is it just me?

I'm on https://search.brave.com/goggles/discover?nav=site and type `Drupal` but Brave gives me no suggestions.

**Comment by kevinquillen** [comment]
Weird. I resubmitted it and now I can see and use it in any browser.

**Comment by MatthieuScarset** [comment]
Indeed! Thank you. I can see clearly now... the rain is gone...
